baseURL = "https://fbirn.github.io/"
languageCode = "en-us"
title = "Fabio Birnegger"
theme = "PaperMod"

[params]
  env = "production"
  description = "Personal Page of Fabio Birnegger"
  author = "Fabio Birnegger"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowToc = true

  # Modern Hero Section
  [params.profileMode]
    enabled = true
    title = "Fabio Birnegger"
    subtitle = "IT-Security | Penetration Testing | Red Teaming"
    imageUrl = "./images/fbirn.jfif"
    imageTitle = "Fabio"
    imageWidth = 220
    imageHeight = 220

    [[params.profileMode.buttons]]
      name = "ðŸ“– Read the Blog"
      url = "/posts"

    [[params.profileMode.buttons]]
      name = "ðŸ’¼ LinkedIn"
      url = "https://linkedin.com/in/DEINUSERNAME"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/fabio-birnegger-22073715a/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/fbirn"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20


ShowCodeCopyButtons = true
ShowToc = true
ShowWordCount = true
